name: Ex3 - interact with Github API with curl
on: 
  pull_request:
    
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
        - name: short_sha
          run: echo 'sha_short=${GITHUB_SHA::7}' >> $GITHUB_OUTPUT
        - name: create issue
          shell: bash
          run: |
            curl --request POST \
            --url https://api.github.com/repos/pcomte-sfeir/sfeir-school-github-actions/issues \
            --header 'authorization: Bearer ${{ secrets.API_TOKEN_REPO }}' \
            --header 'content-type: application/json' \
            --data '{
                "title": "Automated issue for commit: ${{ steps.short_sha.outputs.sha_short }}",
                "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
                }' \
            --fail