name: call reusable workflow
on: 
  workflow_dispatch:

jobs:
    build-npm:
        uses: pcomte-sfeir/sfeir-school-github-actions/.github/workflows/ex4-reusable.yml@main 
        with:
          node_version: 14